from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class ChatMessage(BaseModel):
    role: str = Field(..., description="Role of the sender: 'system', 'user', or 'assistant'")
    content: str = Field(..., description="The textual content of the message")

class ChatRequest(BaseModel):
    messages: List[ChatMessage] = Field(..., description="The conversation history")
    temperature: Optional[float] = Field(0.7, ge=0.0, le=2.0, description="Sampling temperature")
    max_tokens: Optional[int] = Field(None, gt=0, description="Maximum number of tokens to generate")
    
    # Optional Security Context fields for multi-role grade lookup and IDOR prevention testing
    user_id: Optional[str] = Field("teacher-1", description="Identifier of the user")
    student_id: Optional[str] = Field(None, description="Student ID bound to the user context")
    allowed_student_ids: Optional[List[str]] = Field([], description="List of student IDs this user is authorized to query")
    role: Optional[str] = Field("teacher", description="Role of the user (student, teacher, admin)")

class ChatResponseUsage(BaseModel):
    prompt_tokens: int = Field(0, description="Number of tokens in the prompt")
    completion_tokens: int = Field(0, description="Number of tokens in the completion")
    total_tokens: int = Field(0, description="Total number of tokens used")

class ChatResponse(BaseModel):
    reply: str = Field(..., description="The response generated by the assistant")
    model: str = Field(..., description="The model name that generated the response")
    usage: ChatResponseUsage = Field(..., description="Token usage details")
    latency_ms: float = Field(..., description="Total processing time in milliseconds")
